name: Deploy Node.js Server

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  deploy:
    runs-on: self-hosted  # Ensure your self-hosted runner is properly configured

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Move files
      run: cp -r * ~/api_path  # Move all files and folders to /root/api_path

    - name: Install dependencies
      run: cd ~/api_path && yarn install

    - name: Deploy DB
      run: yarn run migrate
    

    # Add more steps for building, testing, starting server, etc.
